package Persistencia;
// Generated Mar 14, 2013 9:27:03 AM by Hibernate Tools 3.2.1.GA



/**
 * Accionmejoramiento generated by hbm2java
 */
public class Accionmejoramiento  implements java.io.Serializable {


     private int idaccion;
     private Plandemejoramiento plandemejoramiento;
     private String mejoramiento;

    public Accionmejoramiento() {
    }

    public Accionmejoramiento(int idaccion, Plandemejoramiento plandemejoramiento, String mejoramiento) {
       this.idaccion = idaccion;
       this.plandemejoramiento = plandemejoramiento;
       this.mejoramiento = mejoramiento;
    }
   
    public int getIdaccion() {
        return this.idaccion;
    }
    
    public void setIdaccion(int idaccion) {
        this.idaccion = idaccion;
    }
    public Plandemejoramiento getPlandemejoramiento() {
        return this.plandemejoramiento;
    }
    
    public void setPlandemejoramiento(Plandemejoramiento plandemejoramiento) {
        this.plandemejoramiento = plandemejoramiento;
    }
    public String getMejoramiento() {
        return this.mejoramiento;
    }
    
    public void setMejoramiento(String mejoramiento) {
        this.mejoramiento = mejoramiento;
    }




}


