package Persistencia;
// Generated Mar 14, 2013 9:27:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int idciudad;
     private Departamento departamento;
     private String codigo;
     private String descciudad;
     private Set funcionariosForIdciudad = new HashSet(0);
     private Set funcionariosForCiuIdciudad = new HashSet(0);
     private Set funcionariosForCiuIdciudad2 = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(int idciudad, Departamento departamento, String codigo, String descciudad) {
        this.idciudad = idciudad;
        this.departamento = departamento;
        this.codigo = codigo;
        this.descciudad = descciudad;
    }
    public Ciudad(int idciudad, Departamento departamento, String codigo, String descciudad, Set funcionariosForIdciudad, Set funcionariosForCiuIdciudad, Set funcionariosForCiuIdciudad2) {
       this.idciudad = idciudad;
       this.departamento = departamento;
       this.codigo = codigo;
       this.descciudad = descciudad;
       this.funcionariosForIdciudad = funcionariosForIdciudad;
       this.funcionariosForCiuIdciudad = funcionariosForCiuIdciudad;
       this.funcionariosForCiuIdciudad2 = funcionariosForCiuIdciudad2;
    }
   
    public int getIdciudad() {
        return this.idciudad;
    }
    
    public void setIdciudad(int idciudad) {
        this.idciudad = idciudad;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescciudad() {
        return this.descciudad;
    }
    
    public void setDescciudad(String descciudad) {
        this.descciudad = descciudad;
    }
    public Set getFuncionariosForIdciudad() {
        return this.funcionariosForIdciudad;
    }
    
    public void setFuncionariosForIdciudad(Set funcionariosForIdciudad) {
        this.funcionariosForIdciudad = funcionariosForIdciudad;
    }
    public Set getFuncionariosForCiuIdciudad() {
        return this.funcionariosForCiuIdciudad;
    }
    
    public void setFuncionariosForCiuIdciudad(Set funcionariosForCiuIdciudad) {
        this.funcionariosForCiuIdciudad = funcionariosForCiuIdciudad;
    }
    public Set getFuncionariosForCiuIdciudad2() {
        return this.funcionariosForCiuIdciudad2;
    }
    
    public void setFuncionariosForCiuIdciudad2(Set funcionariosForCiuIdciudad2) {
        this.funcionariosForCiuIdciudad2 = funcionariosForCiuIdciudad2;
    }




}


