package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private int idclase;
     private String descclase;
     private Set funcionarios = new HashSet(0);

    public Clase() {
    }

	
    public Clase(int idclase, String descclase) {
        this.idclase = idclase;
        this.descclase = descclase;
    }
    public Clase(int idclase, String descclase, Set funcionarios) {
       this.idclase = idclase;
       this.descclase = descclase;
       this.funcionarios = funcionarios;
    }
   
    public int getIdclase() {
        return this.idclase;
    }
    
    public void setIdclase(int idclase) {
        this.idclase = idclase;
    }
    public String getDescclase() {
        return this.descclase;
    }
    
    public void setDescclase(String descclase) {
        this.descclase = descclase;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


