package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma  implements java.io.Serializable {


     private int idcronograma;
     private String desccronograma;
     private Set plandemejoramientos = new HashSet(0);

    public Cronograma() {
    }

	
    public Cronograma(int idcronograma, String desccronograma) {
        this.idcronograma = idcronograma;
        this.desccronograma = desccronograma;
    }
    public Cronograma(int idcronograma, String desccronograma, Set plandemejoramientos) {
       this.idcronograma = idcronograma;
       this.desccronograma = desccronograma;
       this.plandemejoramientos = plandemejoramientos;
    }
   
    public int getIdcronograma() {
        return this.idcronograma;
    }
    
    public void setIdcronograma(int idcronograma) {
        this.idcronograma = idcronograma;
    }
    public String getDesccronograma() {
        return this.desccronograma;
    }
    
    public void setDesccronograma(String desccronograma) {
        this.desccronograma = desccronograma;
    }
    public Set getPlandemejoramientos() {
        return this.plandemejoramientos;
    }
    
    public void setPlandemejoramientos(Set plandemejoramientos) {
        this.plandemejoramientos = plandemejoramientos;
    }




}


