package Persistencia;
// Generated Mar 14, 2013 9:27:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int iddepartamento;
     private String codigo;
     private String descdepartamento;
     private Set ciudads = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int iddepartamento, String codigo, String descdepartamento) {
        this.iddepartamento = iddepartamento;
        this.codigo = codigo;
        this.descdepartamento = descdepartamento;
    }
    public Departamento(int iddepartamento, String codigo, String descdepartamento, Set ciudads) {
       this.iddepartamento = iddepartamento;
       this.codigo = codigo;
       this.descdepartamento = descdepartamento;
       this.ciudads = ciudads;
    }
   
    public int getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescdepartamento() {
        return this.descdepartamento;
    }
    
    public void setDescdepartamento(String descdepartamento) {
        this.descdepartamento = descdepartamento;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }




}


