package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int iddepartamento;
     private String codigoregional;
     private String descdepartamento;
     private Set ciudads = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int iddepartamento, String codigoregional, String descdepartamento) {
        this.iddepartamento = iddepartamento;
        this.codigoregional = codigoregional;
        this.descdepartamento = descdepartamento;
    }
    public Departamento(int iddepartamento, String codigoregional, String descdepartamento, Set ciudads) {
       this.iddepartamento = iddepartamento;
       this.codigoregional = codigoregional;
       this.descdepartamento = descdepartamento;
       this.ciudads = ciudads;
    }
   
    public int getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public String getCodigoregional() {
        return this.codigoregional;
    }
    
    public void setCodigoregional(String codigoregional) {
        this.codigoregional = codigoregional;
    }
    public String getDescdepartamento() {
        return this.descdepartamento;
    }
    
    public void setDescdepartamento(String descdepartamento) {
        this.descdepartamento = descdepartamento;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }




}


