package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int idestado;
     private String descestado;
     private Set procesos = new HashSet(0);
     private Set rols = new HashSet(0);
     private Set riesgos = new HashSet(0);
     private Set funcionarios = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int idestado, String descestado) {
        this.idestado = idestado;
        this.descestado = descestado;
    }
    public Estado(int idestado, String descestado, Set procesos, Set rols, Set riesgos, Set funcionarios) {
       this.idestado = idestado;
       this.descestado = descestado;
       this.procesos = procesos;
       this.rols = rols;
       this.riesgos = riesgos;
       this.funcionarios = funcionarios;
    }
   
    public int getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(int idestado) {
        this.idestado = idestado;
    }
    public String getDescestado() {
        return this.descestado;
    }
    
    public void setDescestado(String descestado) {
        this.descestado = descestado;
    }
    public Set getProcesos() {
        return this.procesos;
    }
    
    public void setProcesos(Set procesos) {
        this.procesos = procesos;
    }
    public Set getRols() {
        return this.rols;
    }
    
    public void setRols(Set rols) {
        this.rols = rols;
    }
    public Set getRiesgos() {
        return this.riesgos;
    }
    
    public void setRiesgos(Set riesgos) {
        this.riesgos = riesgos;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


