package Persistencia;
// Generated 18/09/2014 10:15:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estadomejora generated by hbm2java
 */
public class Estadomejora  implements java.io.Serializable {


     private int idestadomejora;
     private String descestadomejo;
     private Set planmejoramientos = new HashSet(0);

    public Estadomejora() {
    }

	
    public Estadomejora(int idestadomejora, String descestadomejo) {
        this.idestadomejora = idestadomejora;
        this.descestadomejo = descestadomejo;
    }
    public Estadomejora(int idestadomejora, String descestadomejo, Set planmejoramientos) {
       this.idestadomejora = idestadomejora;
       this.descestadomejo = descestadomejo;
       this.planmejoramientos = planmejoramientos;
    }
   
    public int getIdestadomejora() {
        return this.idestadomejora;
    }
    
    public void setIdestadomejora(int idestadomejora) {
        this.idestadomejora = idestadomejora;
    }
    public String getDescestadomejo() {
        return this.descestadomejo;
    }
    
    public void setDescestadomejo(String descestadomejo) {
        this.descestadomejo = descestadomejo;
    }
    public Set getPlanmejoramientos() {
        return this.planmejoramientos;
    }
    
    public void setPlanmejoramientos(Set planmejoramientos) {
        this.planmejoramientos = planmejoramientos;
    }




}


