package Persistencia;
// Generated 8/09/2014 11:38:16 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estadomejoramiento generated by hbm2java
 */
public class Estadomejoramiento  implements java.io.Serializable {


     private int idestadomejoramiento;
     private String descestadomejo;
     private Set plandemejoramientos = new HashSet(0);

    public Estadomejoramiento() {
    }

	
    public Estadomejoramiento(int idestadomejoramiento, String descestadomejo) {
        this.idestadomejoramiento = idestadomejoramiento;
        this.descestadomejo = descestadomejo;
    }
    public Estadomejoramiento(int idestadomejoramiento, String descestadomejo, Set plandemejoramientos) {
       this.idestadomejoramiento = idestadomejoramiento;
       this.descestadomejo = descestadomejo;
       this.plandemejoramientos = plandemejoramientos;
    }
   
    public int getIdestadomejoramiento() {
        return this.idestadomejoramiento;
    }
    
    public void setIdestadomejoramiento(int idestadomejoramiento) {
        this.idestadomejoramiento = idestadomejoramiento;
    }
    public String getDescestadomejo() {
        return this.descestadomejo;
    }
    
    public void setDescestadomejo(String descestadomejo) {
        this.descestadomejo = descestadomejo;
    }
    public Set getPlandemejoramientos() {
        return this.plandemejoramientos;
    }
    
    public void setPlandemejoramientos(Set plandemejoramientos) {
        this.plandemejoramientos = plandemejoramientos;
    }




}


