package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private int idlog;
     private Proceso proceso;
     private Panoramaderiesgos panoramaderiesgos;
     private Funcionario funcionario;
     private Riesgo riesgo;
     private Date fecha;

    public Log() {
    }

    public Log(int idlog, Proceso proceso, Panoramaderiesgos panoramaderiesgos, Funcionario funcionario, Riesgo riesgo, Date fecha) {
       this.idlog = idlog;
       this.proceso = proceso;
       this.panoramaderiesgos = panoramaderiesgos;
       this.funcionario = funcionario;
       this.riesgo = riesgo;
       this.fecha = fecha;
    }
   
    public int getIdlog() {
        return this.idlog;
    }
    
    public void setIdlog(int idlog) {
        this.idlog = idlog;
    }
    public Proceso getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
    }
    public Panoramaderiesgos getPanoramaderiesgos() {
        return this.panoramaderiesgos;
    }
    
    public void setPanoramaderiesgos(Panoramaderiesgos panoramaderiesgos) {
        this.panoramaderiesgos = panoramaderiesgos;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Riesgo getRiesgo() {
        return this.riesgo;
    }
    
    public void setRiesgo(Riesgo riesgo) {
        this.riesgo = riesgo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


