package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Panoramaderiesgos generated by hbm2java
 */
public class Panoramaderiesgos  implements java.io.Serializable {


     private int idpanoramariesgos;
     private Proceso proceso;
     private Riesgo riesgoByIdcausa;
     private Riesgo riesgoByIdriesgo;
     private Set analisisvaloracions = new HashSet(0);
     private Set logs = new HashSet(0);
     private Set plandemejoramientos = new HashSet(0);

    public Panoramaderiesgos() {
    }

	
    public Panoramaderiesgos(int idpanoramariesgos, Proceso proceso, Riesgo riesgoByIdcausa, Riesgo riesgoByIdriesgo) {
        this.idpanoramariesgos = idpanoramariesgos;
        this.proceso = proceso;
        this.riesgoByIdcausa = riesgoByIdcausa;
        this.riesgoByIdriesgo = riesgoByIdriesgo;
    }
    public Panoramaderiesgos(int idpanoramariesgos, Proceso proceso, Riesgo riesgoByIdcausa, Riesgo riesgoByIdriesgo, Set analisisvaloracions, Set logs, Set plandemejoramientos) {
       this.idpanoramariesgos = idpanoramariesgos;
       this.proceso = proceso;
       this.riesgoByIdcausa = riesgoByIdcausa;
       this.riesgoByIdriesgo = riesgoByIdriesgo;
       this.analisisvaloracions = analisisvaloracions;
       this.logs = logs;
       this.plandemejoramientos = plandemejoramientos;
    }
   
    public int getIdpanoramariesgos() {
        return this.idpanoramariesgos;
    }
    
    public void setIdpanoramariesgos(int idpanoramariesgos) {
        this.idpanoramariesgos = idpanoramariesgos;
    }
    public Proceso getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
    }
    public Riesgo getRiesgoByIdcausa() {
        return this.riesgoByIdcausa;
    }
    
    public void setRiesgoByIdcausa(Riesgo riesgoByIdcausa) {
        this.riesgoByIdcausa = riesgoByIdcausa;
    }
    public Riesgo getRiesgoByIdriesgo() {
        return this.riesgoByIdriesgo;
    }
    
    public void setRiesgoByIdriesgo(Riesgo riesgoByIdriesgo) {
        this.riesgoByIdriesgo = riesgoByIdriesgo;
    }
    public Set getAnalisisvaloracions() {
        return this.analisisvaloracions;
    }
    
    public void setAnalisisvaloracions(Set analisisvaloracions) {
        this.analisisvaloracions = analisisvaloracions;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
    public Set getPlandemejoramientos() {
        return this.plandemejoramientos;
    }
    
    public void setPlandemejoramientos(Set plandemejoramientos) {
        this.plandemejoramientos = plandemejoramientos;
    }




}


