package Persistencia;
// Generated 8/09/2014 11:38:16 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Panoramaderiesgos generated by hbm2java
 */
public class Panoramaderiesgos  implements java.io.Serializable {


     private int idpanoramariesgos;
     private Proceso proceso;
     private Riesgo riesgoByRieIdriesgo;
     private Riesgo riesgoByIdriesgo;
     private Set trazapanoramas = new HashSet(0);
     private Set analisisvaloracions = new HashSet(0);
     private Set plandemejoramientos = new HashSet(0);

    public Panoramaderiesgos() {
    }

	
    public Panoramaderiesgos(int idpanoramariesgos, Proceso proceso, Riesgo riesgoByRieIdriesgo, Riesgo riesgoByIdriesgo) {
        this.idpanoramariesgos = idpanoramariesgos;
        this.proceso = proceso;
        this.riesgoByRieIdriesgo = riesgoByRieIdriesgo;
        this.riesgoByIdriesgo = riesgoByIdriesgo;
    }
    public Panoramaderiesgos(int idpanoramariesgos, Proceso proceso, Riesgo riesgoByRieIdriesgo, Riesgo riesgoByIdriesgo, Set trazapanoramas, Set analisisvaloracions, Set plandemejoramientos) {
       this.idpanoramariesgos = idpanoramariesgos;
       this.proceso = proceso;
       this.riesgoByRieIdriesgo = riesgoByRieIdriesgo;
       this.riesgoByIdriesgo = riesgoByIdriesgo;
       this.trazapanoramas = trazapanoramas;
       this.analisisvaloracions = analisisvaloracions;
       this.plandemejoramientos = plandemejoramientos;
    }
   
    public int getIdpanoramariesgos() {
        return this.idpanoramariesgos;
    }
    
    public void setIdpanoramariesgos(int idpanoramariesgos) {
        this.idpanoramariesgos = idpanoramariesgos;
    }
    public Proceso getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
    }
    public Riesgo getRiesgoByRieIdriesgo() {
        return this.riesgoByRieIdriesgo;
    }
    
    public void setRiesgoByRieIdriesgo(Riesgo riesgoByRieIdriesgo) {
        this.riesgoByRieIdriesgo = riesgoByRieIdriesgo;
    }
    public Riesgo getRiesgoByIdriesgo() {
        return this.riesgoByIdriesgo;
    }
    
    public void setRiesgoByIdriesgo(Riesgo riesgoByIdriesgo) {
        this.riesgoByIdriesgo = riesgoByIdriesgo;
    }
    public Set getTrazapanoramas() {
        return this.trazapanoramas;
    }
    
    public void setTrazapanoramas(Set trazapanoramas) {
        this.trazapanoramas = trazapanoramas;
    }
    public Set getAnalisisvaloracions() {
        return this.analisisvaloracions;
    }
    
    public void setAnalisisvaloracions(Set analisisvaloracions) {
        this.analisisvaloracions = analisisvaloracions;
    }
    public Set getPlandemejoramientos() {
        return this.plandemejoramientos;
    }
    
    public void setPlandemejoramientos(Set plandemejoramientos) {
        this.plandemejoramientos = plandemejoramientos;
    }




}


