package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0



/**
 * Plandemejoramiento generated by hbm2java
 */
public class Plandemejoramiento  implements java.io.Serializable {


     private int idmejoramiento;
     private Panoramaderiesgos panoramaderiesgos;
     private Funcionario funcionario;
     private Cronograma cronograma;
     private int resultado;
     private String mejoramiento;

    public Plandemejoramiento() {
    }

    public Plandemejoramiento(int idmejoramiento, Panoramaderiesgos panoramaderiesgos, Funcionario funcionario, Cronograma cronograma, int resultado, String mejoramiento) {
       this.idmejoramiento = idmejoramiento;
       this.panoramaderiesgos = panoramaderiesgos;
       this.funcionario = funcionario;
       this.cronograma = cronograma;
       this.resultado = resultado;
       this.mejoramiento = mejoramiento;
    }
   
    public int getIdmejoramiento() {
        return this.idmejoramiento;
    }
    
    public void setIdmejoramiento(int idmejoramiento) {
        this.idmejoramiento = idmejoramiento;
    }
    public Panoramaderiesgos getPanoramaderiesgos() {
        return this.panoramaderiesgos;
    }
    
    public void setPanoramaderiesgos(Panoramaderiesgos panoramaderiesgos) {
        this.panoramaderiesgos = panoramaderiesgos;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Cronograma getCronograma() {
        return this.cronograma;
    }
    
    public void setCronograma(Cronograma cronograma) {
        this.cronograma = cronograma;
    }
    public int getResultado() {
        return this.resultado;
    }
    
    public void setResultado(int resultado) {
        this.resultado = resultado;
    }
    public String getMejoramiento() {
        return this.mejoramiento;
    }
    
    public void setMejoramiento(String mejoramiento) {
        this.mejoramiento = mejoramiento;
    }




}


