package Persistencia;
// Generated Mar 14, 2013 9:27:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Plandemejoramiento generated by hbm2java
 */
public class Plandemejoramiento  implements java.io.Serializable {


     private int idmejoramiento;
     private Panoramaderiesgos panoramaderiesgos;
     private Funcionario funcionario;
     private Cronograma cronograma;
     private int resultado;
     private Set accionmejoramientos = new HashSet(0);

    public Plandemejoramiento() {
    }

	
    public Plandemejoramiento(int idmejoramiento, Panoramaderiesgos panoramaderiesgos, Funcionario funcionario, Cronograma cronograma, int resultado) {
        this.idmejoramiento = idmejoramiento;
        this.panoramaderiesgos = panoramaderiesgos;
        this.funcionario = funcionario;
        this.cronograma = cronograma;
        this.resultado = resultado;
    }
    public Plandemejoramiento(int idmejoramiento, Panoramaderiesgos panoramaderiesgos, Funcionario funcionario, Cronograma cronograma, int resultado, Set accionmejoramientos) {
       this.idmejoramiento = idmejoramiento;
       this.panoramaderiesgos = panoramaderiesgos;
       this.funcionario = funcionario;
       this.cronograma = cronograma;
       this.resultado = resultado;
       this.accionmejoramientos = accionmejoramientos;
    }
   
    public int getIdmejoramiento() {
        return this.idmejoramiento;
    }
    
    public void setIdmejoramiento(int idmejoramiento) {
        this.idmejoramiento = idmejoramiento;
    }
    public Panoramaderiesgos getPanoramaderiesgos() {
        return this.panoramaderiesgos;
    }
    
    public void setPanoramaderiesgos(Panoramaderiesgos panoramaderiesgos) {
        this.panoramaderiesgos = panoramaderiesgos;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Cronograma getCronograma() {
        return this.cronograma;
    }
    
    public void setCronograma(Cronograma cronograma) {
        this.cronograma = cronograma;
    }
    public int getResultado() {
        return this.resultado;
    }
    
    public void setResultado(int resultado) {
        this.resultado = resultado;
    }
    public Set getAccionmejoramientos() {
        return this.accionmejoramientos;
    }
    
    public void setAccionmejoramientos(Set accionmejoramientos) {
        this.accionmejoramientos = accionmejoramientos;
    }




}


