package Persistencia;
// Generated 8/09/2014 11:38:16 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Plandemejoramiento generated by hbm2java
 */
public class Plandemejoramiento  implements java.io.Serializable {


     private int idmejoramiento;
     private Estadomejoramiento estadomejoramiento;
     private Panoramaderiesgos panoramaderiesgos;
     private Funcionario funcionario;
     private int resultado;
     private String mejoramiento;
     private Date fechainicio;
     private Date fecharevision;
     private Set trazamejoramientos = new HashSet(0);

    public Plandemejoramiento() {
    }

	
    public Plandemejoramiento(int idmejoramiento, Estadomejoramiento estadomejoramiento, Panoramaderiesgos panoramaderiesgos, Funcionario funcionario, int resultado, String mejoramiento, Date fechainicio, Date fecharevision) {
        this.idmejoramiento = idmejoramiento;
        this.estadomejoramiento = estadomejoramiento;
        this.panoramaderiesgos = panoramaderiesgos;
        this.funcionario = funcionario;
        this.resultado = resultado;
        this.mejoramiento = mejoramiento;
        this.fechainicio = fechainicio;
        this.fecharevision = fecharevision;
    }
    public Plandemejoramiento(int idmejoramiento, Estadomejoramiento estadomejoramiento, Panoramaderiesgos panoramaderiesgos, Funcionario funcionario, int resultado, String mejoramiento, Date fechainicio, Date fecharevision, Set trazamejoramientos) {
       this.idmejoramiento = idmejoramiento;
       this.estadomejoramiento = estadomejoramiento;
       this.panoramaderiesgos = panoramaderiesgos;
       this.funcionario = funcionario;
       this.resultado = resultado;
       this.mejoramiento = mejoramiento;
       this.fechainicio = fechainicio;
       this.fecharevision = fecharevision;
       this.trazamejoramientos = trazamejoramientos;
    }
   
    public int getIdmejoramiento() {
        return this.idmejoramiento;
    }
    
    public void setIdmejoramiento(int idmejoramiento) {
        this.idmejoramiento = idmejoramiento;
    }
    public Estadomejoramiento getEstadomejoramiento() {
        return this.estadomejoramiento;
    }
    
    public void setEstadomejoramiento(Estadomejoramiento estadomejoramiento) {
        this.estadomejoramiento = estadomejoramiento;
    }
    public Panoramaderiesgos getPanoramaderiesgos() {
        return this.panoramaderiesgos;
    }
    
    public void setPanoramaderiesgos(Panoramaderiesgos panoramaderiesgos) {
        this.panoramaderiesgos = panoramaderiesgos;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public int getResultado() {
        return this.resultado;
    }
    
    public void setResultado(int resultado) {
        this.resultado = resultado;
    }
    public String getMejoramiento() {
        return this.mejoramiento;
    }
    
    public void setMejoramiento(String mejoramiento) {
        this.mejoramiento = mejoramiento;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFecharevision() {
        return this.fecharevision;
    }
    
    public void setFecharevision(Date fecharevision) {
        this.fecharevision = fecharevision;
    }
    public Set getTrazamejoramientos() {
        return this.trazamejoramientos;
    }
    
    public void setTrazamejoramientos(Set trazamejoramientos) {
        this.trazamejoramientos = trazamejoramientos;
    }




}


