package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proceso generated by hbm2java
 */
public class Proceso  implements java.io.Serializable {


     private int idproceso;
     private Estado estado;
     private Subarea subarea;
     private Procesoasociado procesoasociado;
     private Funcionario funcionario;
     private String codigo;
     private Date creado;
     private Date modificado;
     private Set logs = new HashSet(0);
     private Set panoramaderiesgoses = new HashSet(0);

    public Proceso() {
    }

	
    public Proceso(int idproceso, Estado estado, Subarea subarea, Procesoasociado procesoasociado, Funcionario funcionario, String codigoregional, Date creado) {
        this.idproceso = idproceso;
        this.estado = estado;
        this.subarea = subarea;
        this.procesoasociado = procesoasociado;
        this.funcionario = funcionario;
        this.codigo = codigoregional;
        this.creado = creado;
    }
    public Proceso(int idproceso, Estado estado, Subarea subarea, Procesoasociado procesoasociado, Funcionario funcionario, String codigoregional, Date creado, Date modificado, Set logs, Set panoramaderiesgoses) {
       this.idproceso = idproceso;
       this.estado = estado;
       this.subarea = subarea;
       this.procesoasociado = procesoasociado;
       this.funcionario = funcionario;
       this.codigo = codigoregional;
       this.creado = creado;
       this.modificado = modificado;
       this.logs = logs;
       this.panoramaderiesgoses = panoramaderiesgoses;
    }

    public Proceso(Estado estado, Subarea subarea, Procesoasociado procesoasociado, Funcionario funcionario, String codigoregional, Date creado) {
       this.idproceso = idproceso;
       this.estado = estado;
       this.subarea = subarea;
       this.procesoasociado = procesoasociado;
       this.funcionario = funcionario;
       this.codigo = codigoregional;
       this.creado = creado;
       this.modificado = modificado;
       this.logs = logs;
       this.panoramaderiesgoses = panoramaderiesgoses;
    }
   
    public int getIdproceso() {
        return this.idproceso;
    }
    
    public void setIdproceso(int idproceso) {
        this.idproceso = idproceso;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Subarea getSubarea() {
        return this.subarea;
    }
    
    public void setSubarea(Subarea subarea) {
        this.subarea = subarea;
    }
    public Procesoasociado getProcesoasociado() {
        return this.procesoasociado;
    }
    
    public void setProcesoasociado(Procesoasociado procesoasociado) {
        this.procesoasociado = procesoasociado;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigoregional) {
        this.codigo = codigoregional;
    }
    public Date getCreado() {
        return this.creado;
    }
    
    public void setCreado(Date creado) {
        this.creado = creado;
    }
    public Date getModificado() {
        return this.modificado;
    }
    
    public void setModificado(Date modificado) {
        this.modificado = modificado;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
    public Set getPanoramaderiesgoses() {
        return this.panoramaderiesgoses;
    }
    
    public void setPanoramaderiesgoses(Set panoramaderiesgoses) {
        this.panoramaderiesgoses = panoramaderiesgoses;
    }




}


