package Persistencia;
// Generated Mar 14, 2013 9:27:03 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proceso generated by hbm2java
 */
public class Proceso  implements java.io.Serializable {


     private int idproceso;
     private Estado estado;
     private Subarea subarea;
     private Procesoasociado procesoasociado;
     private Funcionario funcionario;
     private String codigo;
     private Date creado;
     private Date modificado;
     private Set panoramaderiesgoses = new HashSet(0);

    public Proceso() {
    }

	
    public Proceso(int idproceso, Estado estado, Subarea subarea, Procesoasociado procesoasociado, Funcionario funcionario, String codigo, Date creado) {
        this.idproceso = idproceso;
        this.estado = estado;
        this.subarea = subarea;
        this.procesoasociado = procesoasociado;
        this.funcionario = funcionario;
        this.codigo = codigo;
        this.creado = creado;
    }
    
    public Proceso(Estado estado, Subarea subarea, Procesoasociado procesoasociado, Funcionario funcionario, String codigo, Date creado) {
        this.estado = estado;
        this.subarea = subarea;
        this.procesoasociado = procesoasociado;
        this.funcionario = funcionario;
        this.codigo = codigo;
        this.creado = creado;
    }
    public Proceso(int idproceso, Estado estado, Subarea subarea, Procesoasociado procesoasociado, Funcionario funcionario, String codigo, Date creado, Date modificado, Set panoramaderiesgoses) {
       this.idproceso = idproceso;
       this.estado = estado;
       this.subarea = subarea;
       this.procesoasociado = procesoasociado;
       this.funcionario = funcionario;
       this.codigo = codigo;
       this.creado = creado;
       this.modificado = modificado;
       this.panoramaderiesgoses = panoramaderiesgoses;
    }
   
    public int getIdproceso() {
        return this.idproceso;
    }
    
    public void setIdproceso(int idproceso) {
        this.idproceso = idproceso;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Subarea getSubarea() {
        return this.subarea;
    }
    
    public void setSubarea(Subarea subarea) {
        this.subarea = subarea;
    }
    public Procesoasociado getProcesoasociado() {
        return this.procesoasociado;
    }
    
    public void setProcesoasociado(Procesoasociado procesoasociado) {
        this.procesoasociado = procesoasociado;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getCreado() {
        return this.creado;
    }
    
    public void setCreado(Date creado) {
        this.creado = creado;
    }
    public Date getModificado() {
        return this.modificado;
    }
    
    public void setModificado(Date modificado) {
        this.modificado = modificado;
    }
    public Set getPanoramaderiesgoses() {
        return this.panoramaderiesgoses;
    }
    
    public void setPanoramaderiesgoses(Set panoramaderiesgoses) {
        this.panoramaderiesgoses = panoramaderiesgoses;
    }




}


