package Persistencia;
// Generated Mar 14, 2013 9:27:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Regional generated by hbm2java
 */
public class Regional  implements java.io.Serializable {


     private int idregional;
     private String descregional;
     private Set seccionals = new HashSet(0);

    public Regional() {
    }

	
    public Regional(int idregional, String descregional) {
        this.idregional = idregional;
        this.descregional = descregional;
    }
    public Regional(int idregional, String descregional, Set seccionals) {
       this.idregional = idregional;
       this.descregional = descregional;
       this.seccionals = seccionals;
    }
   
    public int getIdregional() {
        return this.idregional;
    }
    
    public void setIdregional(int idregional) {
        this.idregional = idregional;
    }
    public String getDescregional() {
        return this.descregional;
    }
    
    public void setDescregional(String descregional) {
        this.descregional = descregional;
    }
    public Set getSeccionals() {
        return this.seccionals;
    }
    
    public void setSeccionals(Set seccionals) {
        this.seccionals = seccionals;
    }




}


