package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Riesgo generated by hbm2java
 */
public class Riesgo  implements java.io.Serializable {


     private int idriesgo;
     private Estado estado;
     private Enfoque enfoque;
     private Tipo tipo;
     private Clasificacion clasificacion;
     private String nombre;
     private String descripcion;
     private int entrada;
     private Set panoramaderiesgosesForIdcausa = new HashSet(0);
     private Set panoramaderiesgosesForIdriesgo = new HashSet(0);
     private Set logs = new HashSet(0);

    public Riesgo() {
    }

	
    public Riesgo(int idriesgo, Estado estado, Enfoque enfoque, Tipo tipo, Clasificacion clasificacion, String nombre, String descripcion, int entrada) {
        this.idriesgo = idriesgo;
        this.estado = estado;
        this.enfoque = enfoque;
        this.tipo = tipo;
        this.clasificacion = clasificacion;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.entrada = entrada;
    }
    public Riesgo(int idriesgo, Estado estado, Enfoque enfoque, Tipo tipo, Clasificacion clasificacion, String nombre, String descripcion, int entrada, Set panoramaderiesgosesForIdcausa, Set panoramaderiesgosesForIdriesgo, Set logs) {
       this.idriesgo = idriesgo;
       this.estado = estado;
       this.enfoque = enfoque;
       this.tipo = tipo;
       this.clasificacion = clasificacion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.entrada = entrada;
       this.panoramaderiesgosesForIdcausa = panoramaderiesgosesForIdcausa;
       this.panoramaderiesgosesForIdriesgo = panoramaderiesgosesForIdriesgo;
       this.logs = logs;
    }
   
    public int getIdriesgo() {
        return this.idriesgo;
    }
    
    public void setIdriesgo(int idriesgo) {
        this.idriesgo = idriesgo;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Enfoque getEnfoque() {
        return this.enfoque;
    }
    
    public void setEnfoque(Enfoque enfoque) {
        this.enfoque = enfoque;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public Clasificacion getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(Clasificacion clasificacion) {
        this.clasificacion = clasificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(int entrada) {
        this.entrada = entrada;
    }
    public Set getPanoramaderiesgosesForIdcausa() {
        return this.panoramaderiesgosesForIdcausa;
    }
    
    public void setPanoramaderiesgosesForIdcausa(Set panoramaderiesgosesForIdcausa) {
        this.panoramaderiesgosesForIdcausa = panoramaderiesgosesForIdcausa;
    }
    public Set getPanoramaderiesgosesForIdriesgo() {
        return this.panoramaderiesgosesForIdriesgo;
    }
    
    public void setPanoramaderiesgosesForIdriesgo(Set panoramaderiesgosesForIdriesgo) {
        this.panoramaderiesgosesForIdriesgo = panoramaderiesgosesForIdriesgo;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }




}


