package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subarea generated by hbm2java
 */
public class Subarea  implements java.io.Serializable {


     private int idsubarea;
     private Area area;
     private String descsubarea;
     private String codigosubarea;
     private Set procesos = new HashSet(0);
     private Set funcionarios = new HashSet(0);

    public Subarea() {
    }

	
    public Subarea(int idsubarea, Area area, String descsubarea, String codigosubarea) {
        this.idsubarea = idsubarea;
        this.area = area;
        this.descsubarea = descsubarea;
        this.codigosubarea = codigosubarea;
    }
    public Subarea(int idsubarea, Area area, String descsubarea, String codigosubarea, Set procesos, Set funcionarios) {
       this.idsubarea = idsubarea;
       this.area = area;
       this.descsubarea = descsubarea;
       this.codigosubarea = codigosubarea;
       this.procesos = procesos;
       this.funcionarios = funcionarios;
    }
   
    public int getIdsubarea() {
        return this.idsubarea;
    }
    
    public void setIdsubarea(int idsubarea) {
        this.idsubarea = idsubarea;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public String getDescsubarea() {
        return this.descsubarea;
    }
    
    public void setDescsubarea(String descsubarea) {
        this.descsubarea = descsubarea;
    }
    public String getCodigosubarea() {
        return this.codigosubarea;
    }
    
    public void setCodigosubarea(String codigosubarea) {
        this.codigosubarea = codigosubarea;
    }
    public Set getProcesos() {
        return this.procesos;
    }
    
    public void setProcesos(Set procesos) {
        this.procesos = procesos;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


