package Persistencia;
// Generated 21/07/2014 10:05:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private int idtipo;
     private String desctiporiesgo;
     private Set riesgos = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(int idtipo, String desctiporiesgo) {
        this.idtipo = idtipo;
        this.desctiporiesgo = desctiporiesgo;
    }
    public Tipo(int idtipo, String desctiporiesgo, Set riesgos) {
       this.idtipo = idtipo;
       this.desctiporiesgo = desctiporiesgo;
       this.riesgos = riesgos;
    }
   
    public int getIdtipo() {
        return this.idtipo;
    }
    
    public void setIdtipo(int idtipo) {
        this.idtipo = idtipo;
    }
    public String getDesctiporiesgo() {
        return this.desctiporiesgo;
    }
    
    public void setDesctiporiesgo(String desctiporiesgo) {
        this.desctiporiesgo = desctiporiesgo;
    }
    public Set getRiesgos() {
        return this.riesgos;
    }
    
    public void setRiesgos(Set riesgos) {
        this.riesgos = riesgos;
    }




}


