package Persistencia;
// Generated 18/09/2014 10:15:52 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trazavaloracion generated by hbm2java
 */
public class Trazavaloracion  implements java.io.Serializable {


     private int idtrazavaloracion;
     private String proceso;
     private String riesgo;
     private int origin;
     private int probabilidad;
     private int impacto;
     private int control;
     private String usuariooperacion;
     private Date fechaoperacion;
     private String tipooperacion;
     private Set analisisvaloracions = new HashSet(0);

    public Trazavaloracion() {
    }

	
    public Trazavaloracion(int idtrazavaloracion, String proceso, String riesgo, int origin, int probabilidad, int impacto, int control, String usuariooperacion, Date fechaoperacion, String tipooperacion) {
        this.idtrazavaloracion = idtrazavaloracion;
        this.proceso = proceso;
        this.riesgo = riesgo;
        this.origin = origin;
        this.probabilidad = probabilidad;
        this.impacto = impacto;
        this.control = control;
        this.usuariooperacion = usuariooperacion;
        this.fechaoperacion = fechaoperacion;
        this.tipooperacion = tipooperacion;
    }
    public Trazavaloracion(int idtrazavaloracion, String proceso, String riesgo, int origin, int probabilidad, int impacto, int control, String usuariooperacion, Date fechaoperacion, String tipooperacion, Set analisisvaloracions) {
       this.idtrazavaloracion = idtrazavaloracion;
       this.proceso = proceso;
       this.riesgo = riesgo;
       this.origin = origin;
       this.probabilidad = probabilidad;
       this.impacto = impacto;
       this.control = control;
       this.usuariooperacion = usuariooperacion;
       this.fechaoperacion = fechaoperacion;
       this.tipooperacion = tipooperacion;
       this.analisisvaloracions = analisisvaloracions;
    }
   
    public int getIdtrazavaloracion() {
        return this.idtrazavaloracion;
    }
    
    public void setIdtrazavaloracion(int idtrazavaloracion) {
        this.idtrazavaloracion = idtrazavaloracion;
    }
    public String getProceso() {
        return this.proceso;
    }
    
    public void setProceso(String proceso) {
        this.proceso = proceso;
    }
    public String getRiesgo() {
        return this.riesgo;
    }
    
    public void setRiesgo(String riesgo) {
        this.riesgo = riesgo;
    }
    public int getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(int origin) {
        this.origin = origin;
    }
    public int getProbabilidad() {
        return this.probabilidad;
    }
    
    public void setProbabilidad(int probabilidad) {
        this.probabilidad = probabilidad;
    }
    public int getImpacto() {
        return this.impacto;
    }
    
    public void setImpacto(int impacto) {
        this.impacto = impacto;
    }
    public int getControl() {
        return this.control;
    }
    
    public void setControl(int control) {
        this.control = control;
    }
    public String getUsuariooperacion() {
        return this.usuariooperacion;
    }
    
    public void setUsuariooperacion(String usuariooperacion) {
        this.usuariooperacion = usuariooperacion;
    }
    public Date getFechaoperacion() {
        return this.fechaoperacion;
    }
    
    public void setFechaoperacion(Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }
    public String getTipooperacion() {
        return this.tipooperacion;
    }
    
    public void setTipooperacion(String tipooperacion) {
        this.tipooperacion = tipooperacion;
    }
    public Set getAnalisisvaloracions() {
        return this.analisisvaloracions;
    }
    
    public void setAnalisisvaloracions(Set analisisvaloracions) {
        this.analisisvaloracions = analisisvaloracions;
    }




}


